#!/bin/bash

docker run --name respira-java -p 8080:8080 -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
	AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
	AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
	SLACK_HOOK_SAUDE=${SLACK_HOOK_SAUDE} \
	SLACK_HOOK_AMBIENTAL=${SLACK_HOOK_AMBIENTAL} \
	DB_USER=${DB_USER} \
	DB_PASSWORD=${DB_PASSWORD} furqas/respira-java-data:latest
