services:
  web:
    image: furqas/respira-web:latest
    container_name: respira-web
    restart: always
    hostname: localhost
    environment:
      - APP_PORT=3000
      - APP_HOST=${APP_HOST}
      - AMBIENTE_PROCESSO=producao
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=Respira
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=3306
    ports:
      - "3000:3000"
    networks:
      - respira-network   

networks:
  respira-network:
    name: respira-network
    driver: bridge
volumes:
  mysql_data:
