name: Builda as imagens do projeto e faz o push para o docker hub

on:
    pull_request:
        branches: ["dev"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login Docker Hub
              run: sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Realiza o build da imagem do Java
              run: docker build --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --build-arg AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} -t furqas/respira-java-data -f ./LOGgrupo2/Dockerfile .

            - name: Push image docker
              run: sudo docker push furqas/respira-java-data

